### ISSUE TITLE
Charset problem

### ISSUE THREAD

**Issue by masterbug** [xbmc/audioencoder.lame#38]
Hello,

 Like this addon. But I have a problem, it does not handle äöü and so on correctly.
The ACC encoder does it right. Maybe you can apply the same charset handling also to the Lame Encoder.
The Filename appears correct, but Kodi displays it wrong. As far as I know this is because of wrong or false charset handling.
 Applies to 2.0.x and also to 3.x
regards
Masterbug

**Comment by masterbug** [comment]
Here is a picture: 
![image](https://user-images.githubusercontent.com/1392383/130229477-eb24180d-84e6-41f8-8cae-8e6749357131.jpg)
And when I display the same in FileExplorer:
![001CF864-93CB-4FA0-B6FA-712A9C7829AD](https://user-images.githubusercontent.com/1392383/130229590-118cb947-37cb-49d1-8ae6-02e05b009e91.jpeg)

**Comment by AlwinEsch** [comment]
Have something about in mind.
I look to fix it, which OS you used about?

**Comment by AlwinEsch** [comment]
If you have Windows, OSX or Android, can you take for test purposes a zip from from here and install by you for test?
- https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Faudioencoder.lame/detail/PR-40/1/artifacts

About company work I'm currently not at home (Hotel room) and not have CD's for test available.

I'm created on https://github.com/xbmc/audioencoder.lame/pull/40 an request where becomes the latest liblame added, badly they have on them still no new releases, but if it works, maybe we find a way.

**Comment by masterbug** [comment]
Hello, sorry for the late reply.  
it is great to see somebody is looking in this.
I use LibreElec generic for my AllinOne PC. Is there a way to test it with this device?

may I test with Nexus builds?
rgds
Masterbug

**Comment by AlwinEsch** [comment]
A little more difficult, I'll buy a CD tomorrow and test it.
Funnily enough, I'm back for work and home is far away (Saarbrücken at home, and 2 weeks back to work in Frankfurt) :sweat_smile: .

Hadn't thought of it at home either.

**Comment by masterbug** [comment]
Hi, 
I can also send you a CD of Benjamin Blümchen. This works well to demonstrate its issue.
Greetings 
Meanwhile I am on Libreelec 10 with Kodi 19.1 using Lame MP3 Audio Encoder 19.0.0.1 by spiff.

**Comment by AlwinEsch** [comment]
Have becomed it fixed now and here a fix request about https://github.com/xbmc/audioencoder.lame/pull/44.

The UTF-8 was come in strange format, not only in Kodi, also VLC has shown wrong. The fix sets the string format to UTF-16 and with them it has shown correct.

**Comment by AlwinEsch** [comment]
Have brought in the fix requests to Matrix and Nexus version. Hope the libreelec includes soon the update about.

**Comment by masterbug** [comment]
This is good to know. Thank you for your work.

**Comment by masterbug** [comment]
Hello,
With the release of Libreelec 10.0.2 the fix reached finally my device as well. I can now rip Benjamin Blümchen.
Thank you for your effort.
